kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-wp
  namespace: thierry-space
  labels:
    app: wp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
