apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-20g-rwm
  namespace: thierry-space
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfs/kubernetes/dd6
    server: 192.168.1.2
