apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-proxy
  namespace: thierry-space
  labels:
    app: wp-proxysql
data:
  configProxy.sh: |
    #!/bin/bash

    echo "##################"
    echo "#  CONF PROXY    "
    echo "##################"
  
    #test if client mysql is ready
    until mysql -u admin -padmin -h 127.0.0.1 -P6032 -e "SELECT 1"
    do
      echo "-----> Waiting for Proxy..."
      sleep 2
    done
    
    echo "-----> Proxy is up"

    #test if mysql master service is up
    echo "-----> Try to Connect to master-bdd-as with user $WP_DB_ADMIN_USER..."
    mysql -u $WP_DB_ADMIN_USER -p$WP_DB_ADMIN_PASS -h master-bdd-as -e "SELECT 1" || exit 1
    echo "-----> Connexion to master-bdd-as with user $WP_DB_ADMIN_USER OK"  
    
    #test if mysql slave service is up
    echo "-----> Try to Connect to slave-bdd-as with user $WP_DB_ADMIN_USER..."
    mysql -u $WP_DB_ADMIN_USER -p$WP_DB_ADMIN_PASS -h slave-bdd-as -e "SELECT 1" || exit 1
    echo "----->Connexion test to slave-bdd-as with user $mysqlWordpressUser OK" 
    
    #insert Master Service to proxy	
    sqlcmd="INSERT INTO mysql_servers(hostgroup_id,hostname,port) VALUES (1,'master-bdd-as',3306)"
    mysql -u admin -padmin -h 127.0.0.1 -P 6032 -e "$sqlcmd"

    #insert Slave Service to proxy	
    sqlcmd="INSERT INTO mysql_servers(hostgroup_id,hostname,port) VALUES (2,'slave-bdd-as',3306)"
    mysql -u admin -padmin -h 127.0.0.1 -P 6032 -e "$sqlcmd"
    
    echo "-----> Slave and Master created in Proxy" 
      
    mysql -u admin -padmin -h 127.0.0.1 -P 6032 <<EOF
    UPDATE global_variables SET variable_value='$BDD_ADMIN_USER' WHERE variable_name='mysql-monitor_username';
    UPDATE global_variables SET variable_value='$BDD_ADMIN_PASS' WHERE variable_name='mysql-monitor_password';
    UPDATE global_variables SET variable_value='2000' WHERE variable_name IN ('mysql-monitor_connect_interval','mysql-monitor_ping_interval','mysql-monitor_read_only_interval');
    UPDATE global_variables SET variable_value='2000' WHERE variable_name='mysql-connection_max_age_ms';
    UPDATE global_variables SET variable_value='true' WHERE variable_name='mysql-monitor_writer_is_also_reader';
    UPDATE global_variables SET variable_value='200' WHERE variable_name='mysql-connect_timeout_server';  
    UPDATE global_variables SET variable_value='3000' WHERE variable_name='mysql-connect_timeout_server_max';  
    LOAD MYSQL VARIABLES TO RUNTIME;
    SAVE MYSQL VARIABLES TO DISK;
    EOF
    echo "-----> Serveurs et monitoring configures"  

    mysql -u admin -padmin -h 127.0.0.1 -P 6032 <<EOF
    LOAD MYSQL SERVERS TO RUNTIME;
    INSERT INTO mysql_replication_hostgroups VALUES (1,2,'group comment');
    EOF

    
    echo "----> Hostgroups config"  
    mysql -u admin -padmin -h 127.0.0.1 -P 6032 <<EOF
    LOAD MYSQL SERVERS TO RUNTIME;
    INSERT INTO mysql_users(username,password,default_hostgroup) VALUES ('root','$MYSQL_ROOT_PASS',1);
    INSERT INTO mysql_users(username,password,default_hostgroup) VALUES ('$WP_DB_ADMIN_USER','$WP_DB_ADMIN_PASS',1);
    LOAD MYSQL USERS TO RUNTIME;
    SAVE MYSQL USERS TO DISK;
    INSERT INTO mysql_query_rules (rule_id,active,flagIN,match_pattern,negate_match_pattern,destination_hostgroup,apply) VALUES (1,1,0,'^SELECT.*FOR UPDATE$',0,1,1);
    #INSERT INTO mysql_query_rules (rule_id,active,flagIN,match_pattern,negate_match_pattern,destination_hostgroup,apply) VALUES (2,1,0,'^SELECT autoload',0,1,1);
    INSERT INTO mysql_query_rules (rule_id,active,flagIN,match_pattern,negate_match_pattern,destination_hostgroup,apply) VALUES (2,1,0,'^.*wp_options',0,1,1);
    INSERT INTO mysql_query_rules (rule_id,active,flagIN,match_pattern,negate_match_pattern,destination_hostgroup,cache_ttl,apply) VALUES (3,1,0,'^SELECT',0,2,100,1);
    INSERT INTO mysql_query_rules (rule_id,active,flagIN,match_pattern,negate_match_pattern,destination_hostgroup,cache_ttl,apply) VALUES (4,1,0,'^SHOW',0,2,100,1);
    LOAD MYSQL QUERY RULES TO RUNTIME; 
    EOF
    echo "################################"
    echo "Configuration du proxy terminée "
    echo "################################"
    while true
      do
      sleep 3600	
    done
