apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dd-master
  namespace: thierry-space
  labels:
    app: bdd-as
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
