kind: Service
apiVersion: v1
metadata:
  name: master-bdd-as
  namespace: thierry-space
  labels:
    app: bdd-as
spec:
  selector:
    app: bdd-as
    role: master
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
